Fix missing initializer warnings in gio/tests/gdbus-example-subtree.c
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-example-subtree.c:1:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-example-subtree.c:228:1: error: missing initializer for field ‘get_property’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-example-subtree.c:1:
gio/gdbusconnection.h:387:33: note: ‘get_property’ declared here
   GDBusInterfaceGetPropertyFunc get_property;
                                 ^~~~~~~~~~~~
gio/tests/gdbus-example-subtree.c:325:1: error: missing initializer for field ‘padding’ of ‘GDBusSubtreeVTable’ {aka ‘const struct _GDBusSubtreeVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-example-subtree.c:1:
gio/gdbusconnection.h:533:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~