gerror: Document the disadvantages of using GError
And move the discussion to a new subsection in the GError documentation.
Follow-up from commit 04662a8667c8bf0a594f0c6db7291066c272ad38.

https://bugzilla.gnome.org/show_bug.cgi?id=743011