Fixing missing initializer in gobject/gparam.c
gobject/gparam.c: In function ‘g_param_type_register_static’:
gobject/gparam.c:1404:3: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘struct _GTypeInfo’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gobject/gvalue.h:26,
                 from gobject/gparam.h:26,
                 from gobject/gparam.c:26:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~