Fix missing initializer warnings in gio/tests/gsubprocess.c
gio/tests/gsubprocess.c: In function ‘test_communicate_async’:
gio/tests/gsubprocess.c:775:3: error: missing initializer for field ‘running’ of ‘TestAsyncCommunicateData’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TestAsyncCommunicateData data = { flags, 0, };
   ^~~~~~~~~~~~~~~~~~~~~~~~
gio/tests/gsubprocess.c:705:12: note: ‘running’ declared here
   gboolean running;
            ^~~~~~~
gio/tests/gsubprocess.c: In function ‘test_communicate_utf8_async’:
gio/tests/gsubprocess.c:1026:3: error: missing initializer for field ‘running’ of ‘TestAsyncCommunicateData’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TestAsyncCommunicateData data = { flags, 0, };
   ^~~~~~~~~~~~~~~~~~~~~~~~
gio/tests/gsubprocess.c:705:12: note: ‘running’ declared here
   gboolean running;
            ^~~~~~~
gio/tests/gsubprocess.c: In function ‘test_communicate_utf8_cancelled_async’:
gio/tests/gsubprocess.c:1059:3: error: missing initializer for field ‘running’ of ‘TestAsyncCommunicateData’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TestAsyncCommunicateData data = { flags, 0, };
   ^~~~~~~~~~~~~~~~~~~~~~~~
gio/tests/gsubprocess.c:705:12: note: ‘running’ declared here
   gboolean running;
            ^~~~~~~
gio/tests/gsubprocess.c: In function ‘test_communicate_utf8_async_invalid’:
gio/tests/gsubprocess.c:1203:3: error: missing initializer for field ‘running’ of ‘TestAsyncCommunicateData’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TestAsyncCommunicateData data = { flags, 0, };
   ^~~~~~~~~~~~~~~~~~~~~~~~
gio/tests/gsubprocess.c:705:12: note: ‘running’ declared here
   gboolean running;
            ^~~~~~~