Fix missing initializer warning in gio/gdbusobjectmanagerserver.c
gio/gdbusobjectmanagerserver.c:892:1: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gdbusobjectmanagerserver.c:28:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~