gtimezone: compile parse_footertz only if G_OS_UNIX
This pacifies a GCC warning “../glib/gtimezone.c:1559:1: error:
'parse_footertz' defined but not used [-Werror=unused-function]”
on msys2-mingw32.