Fixed missing initializer warning in gobject/tests/ifaceproperties.c
gobject/tests/ifaceproperties.c: In function ‘test_iface_get_type’:
gobject/tests/ifaceproperties.c:144:1: error: missing initializer for field ‘class_finalize’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
 static DEFINE_IFACE (TestIface, test_iface, NULL, test_iface_default_init)
 ^~~~~~
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from gobject/tests/ifaceproperties.c:21:
gobject/gtype.h:1049:26: note: ‘class_finalize’ declared here
   GClassFinalizeFunc     class_finalize;
                          ^~~~~~~~~~~~~~
gobject/tests/ifaceproperties.c: In function ‘base_object_get_type’:
gobject/tests/ifaceproperties.c:321:1: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
 static DEFINE_TYPE_FULL (BaseObject, base_object,
 ^~~~~~
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from gobject/tests/ifaceproperties.c:21:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~
gobject/tests/ifaceproperties.c: In function ‘derived_object_get_type’:
gobject/tests/ifaceproperties.c:389:1: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
 static DEFINE_TYPE (DerivedObject, derived_object,
 ^~~~~~
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from gobject/tests/ifaceproperties.c:21:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~