Fix missing initializer warning in gio/gio-tool-monitor.c
gio/gio-tool-monitor.c:48:3: error: missing initializer for field ‘description’ of ‘GOptionEntry’ {aka ‘const struct _GOptionEntry’} [-Werror=missing-field-initializers]
   { G_OPTION_REMAINING, 0, 0, G_OPTION_ARG_FILENAME_ARRAY, &watch_default },
   ^
In file included from glib/glib.h:64,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gio.h:26,
                 from gio/gio-tool-monitor.c:22:
glib/goption.h:266:16: note: ‘description’ declared here
   const gchar *description;
                ^~~~~~~~~~~