Fix missing initializer warning in gio/gcancellable.c
gio/gcancellable.c:724:1: error: missing initializer for field ‘closure_marshal’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
 };
 ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from gio/gcancellable.c:22:
glib/gmain.h:263:23: note: ‘closure_marshal’ declared here
   GSourceDummyMarshal closure_marshal; /* Really is of type GClosureMarshal */
                       ^~~~~~~~~~~~~~~