gioerror: Handle EMLINK error as too-many-links error
This used to be a FreeBSD only error but it's actually defined also in
linux.

(cherry-picked from commit 9e09894414ca092a07cd094b4fad1fdab0906a9)