Fix missing initializer warnings in gio/tests/basic-application.c
gio/tests/basic-application.c: In function ‘startup’:
gio/tests/basic-application.c:57:5: error: missing initializer for field ‘padding’ of ‘GActionEntry’ {aka ‘struct _GActionEntry’} [-Werror=missing-field-initializers]
     { "new", new_activated, NULL, NULL, NULL },
     ^
In file included from gio/gio.h:31,
                 from gio/tests/basic-application.c:1:
gio/gactionmap.h:72:9: note: ‘padding’ declared here
   gsize padding[3];
         ^~~~~~~
gio/tests/basic-application.c:58:5: error: missing initializer for field ‘padding’ of ‘GActionEntry’ {aka ‘struct _GActionEntry’} [-Werror=missing-field-initializers]
     { "quit", quit_activated, NULL, NULL, NULL },
     ^
In file included from gio/gio.h:31,
                 from gio/tests/basic-application.c:1:
gio/gactionmap.h:72:9: note: ‘padding’ declared here
   gsize padding[3];
         ^~~~~~~
gio/tests/basic-application.c:59:5: error: missing initializer for field ‘padding’ of ‘GActionEntry’ {aka ‘struct _GActionEntry’} [-Werror=missing-field-initializers]
     { "action1", action1_activated, NULL, NULL, NULL },
     ^
In file included from gio/gio.h:31,
                 from gio/tests/basic-application.c:1:
gio/gactionmap.h:72:9: note: ‘padding’ declared here
   gsize padding[3];
         ^~~~~~~
gio/tests/basic-application.c:60:5: error: missing initializer for field ‘padding’ of ‘GActionEntry’ {aka ‘struct _GActionEntry’} [-Werror=missing-field-initializers]
     { "action2", action2_activated, "b", "false", change_action2 }
     ^
In file included from gio/gio.h:31,
                 from gio/tests/basic-application.c:1:
gio/gactionmap.h:72:9: note: ‘padding’ declared here
   gsize padding[3];
         ^~~~~~~