Fix missing initializer warnings in tests/gobject/testgobject.c
tests/gobject/testgobject.c: In function ‘test_iface_get_type’:
tests/gobject/testgobject.c:53:7: error: missing initializer for field ‘class_init’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
       };
       ^
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from tests/gobject/testgobject.c:22:
gobject/gtype.h:1048:26: note: ‘class_init’ declared here
   GClassInitFunc         class_init;
                          ^~~~~~~~~~
tests/gobject/testgobject.c: In function ‘test_object_get_type’:
tests/gobject/testgobject.c:182:7: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
       };
       ^
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from tests/gobject/testgobject.c:22:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~
tests/gobject/testgobject.c: In function ‘derived_object_get_type’:
tests/gobject/testgobject.c:349:7: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
       };
       ^
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from tests/gobject/testgobject.c:22:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~