Fix missing initializer warning in gio/gkeyfilesettingsbackend.c
gio/gkeyfilesettingsbackend.c: In function ‘g_keyfile_settings_backend_write_tree’:
gio/gkeyfilesettingsbackend.c:360:3: error: missing initializer for field ‘failed’ of ‘WriteManyData’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   WriteManyData data = { G_KEYFILE_SETTINGS_BACKEND (backend) };
   ^~~~~~~~~~~~~
gio/gkeyfilesettingsbackend.c:327:12: note: ‘failed’ declared here
   gboolean failed;
            ^~~~~~