timezone: Initialize a local variable
There is a "goto utf16_conv_failed" before in case subkey_w is NULL.
In that case, we're calling g_free() on uninitialized memory.

Fixes this compiler warning:

../subprojects/glib/glib/gtimezone.c:979:3: error: 'subkey_dynamic_w' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  979 |   g_free (subkey_dynamic_w);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~

Found in the gtk windows build.