gstring: fix unused-result warning with g_string_free() in C++
Some g++ versions issue an unused-result warning for the g_string_free() macro:

error: ignoring return value of 'gchar* g_string_free_and_steal(GString*)',
declared with attribute warn_unused_result [-Werror=unused-result]
    g_string_free(s, TRUE);

This occurs with gcc 6.x / 7.1 / 7.2, and it is fixed in gcc 7.3.