Fix missing initializer warning in tests/gobject/testcommon.h
tests/gobject/override.c: In function ‘test_i_get_type’:
tests/gobject/override.c:76:1: error: missing initializer for field ‘class_finalize’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
 static DEFINE_IFACE (TestI, test_i, NULL, test_i_default_init)
 ^~~~~~
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from tests/gobject/override.c:32:
gobject/gtype.h:1049:26: note: ‘class_finalize’ declared here
   GClassFinalizeFunc     class_finalize;
                          ^~~~~~~~~~~~~~