glib-mkenums: require at least one input file
Previously, the behaviour if you supplied no input files was to crash:

    Traceback (most recent call last):
      File "/usr/bin/glib-mkenums", line 420, in <module>
        base = os.path.basename(options.args[0])
    IndexError: list index out of range

While in theory you might want to supply no input files, it is much more
likely to be a misconfiguration of the build process. Since this has
never worked, let's make that explicit:

    glib-mkenums: error: the following arguments are required: args