Fix missing initializer warning in gio/gvdb/gvdb-builder.c
gio/gvdb/gvdb-builder.c: In function ‘file_builder_serialise’:
gio/gvdb/gvdb-builder.c:457:10: error: missing initializer for field ‘version’ of ‘struct gvdb_header’ [-Werror=missing-field-initializers]
   struct gvdb_header header = { { 0, }, };
          ^~~~~~~~~~~
In file included from gio/gvdb/gvdb-builder.c:21:
gio/gvdb/gvdb-format.h:56:14: note: ‘version’ declared here
   guint32_le version;
              ^~~~~~~