Fix missing initializer warning in gio/inotify/inotify-kernel.c
gio/inotify/inotify-kernel.c: In function ‘ik_source_new’:
gio/inotify/inotify-kernel.c:374:3: error: missing initializer for field ‘finalize’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
   };
   ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from gio/inotify/inotify-kernel.c:30:
glib/gmain.h:258:14: note: ‘finalize’ declared here
   void     (*finalize) (GSource    *source); /* Can be NULL */
              ^~~~~~~~