Fix missing initializer warning in gio/gsettingsschema.c
gio/gsettingsschema.c: In function ‘parse_into_text_tables’:
gio/gsettingsschema.c:673:3: error: missing initializer for field ‘passthrough’ of ‘GMarkupParser’ {aka ‘struct _GMarkupParser’} [-Werror=missing-field-initializers]
   GMarkupParser parser = { start_element, end_element, text };
   ^~~~~~~~~~~~~
In file included from glib/glib.h:60,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gsettingsschema.h:22,
                 from gio/gsettingsschema-internal.h:21,
                 from gio/gsettingsschema.c:21:
glib/gmarkup.h:172:10: note: ‘passthrough’ declared here
   void (*passthrough)    (GMarkupParseContext *context,
          ^~~~~~~~~~~
gio/gsettingsschema.c:674:3: error: missing initializer for field ‘gettext_domain’ of ‘TextTableParseInfo’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TextTableParseInfo info = { summaries, descriptions };
   ^~~~~~~~~~~~~~~~~~
gio/gsettingsschema.c:464:15: note: ‘gettext_domain’ declared here
   GSList     *gettext_domain;
               ^~~~~~~~~~~~~~