gnulib: Fix unused flags variable warning
The following error has just popped up in mingw32 CI, which presumably
means the compiler has just been upgraded under our feet again:
```
../glib/gnulib/vasnprintf.c: In function '_g_gnulib_vasnprintf':
../glib/gnulib/vasnprintf.c:2429:21: error: variable 'flags' set but not used [-Werror=unused-but-set-variable=]
 2429 |                 int flags = dp->flags;
      |                     ^~~~~
cc1.exe: all warnings being treated as errors
```

This highlighted a bug in the version of gnulib we’re using, where the
`flags` variable was assigned but never used.

In lieu of updating our gnulib copylib version (which I don’t have the
energy to do right now; see #2603), copy across the fix for this issue
from upstream.

It’s upstream commit 5527d5c548702b89d217bbe58036996066a709b6.

Signed-off-by: Philip Withnall <pwithnall@gnome.org>