Fixing missing initializer in gobject/tests/dynamictests.c
gobject/tests/dynamictests.c: In function ‘test_module_get_type’:
gobject/tests/dynamictests.c:97:7: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
       };
       ^
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from gobject/tests/dynamictests.c:23:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~