Fix missing field initializers in glib/deprecated/gthread.h
glib/deprecated/gthread-deprecated.c:471:42: error: missing field 'unused' initializer [-Werror,-Wmissing-field-initializers]
  static const GStaticMutex init_mutex = G_STATIC_MUTEX_INIT;
                                         ^
glib/deprecated/gthread.h:132:36: note: expanded from macro 'G_STATIC_MUTEX_INIT'
                                   ^
glib/deprecated/gthread-deprecated.c:657:45: error: missing field 'unused' initializer [-Werror,-Wmissing-field-initializers]
  static const GStaticRecMutex init_mutex = G_STATIC_REC_MUTEX_INIT;
                                            ^
glib/deprecated/gthread.h:174:35: note: expanded from macro 'G_STATIC_REC_MUTEX_INIT'
                                  ^
glib/deprecated/gthread.h:132:36: note: expanded from macro 'G_STATIC_MUTEX_INIT'
                                   ^
glib/deprecated/gthread-deprecated.c:957:42: error: missing field 'unused' initializer [-Werror,-Wmissing-field-initializers]
  static const GStaticRWLock init_lock = G_STATIC_RW_LOCK_INIT;
                                         ^
glib/deprecated/gthread.h:210:33: note: expanded from macro 'G_STATIC_RW_LOCK_INIT'
                                ^
glib/deprecated/gthread.h:132:36: note: expanded from macro 'G_STATIC_MUTEX_INIT'
                                   ^