Fix missing initializer warnings in gio/gapplicationimpl-dbus.c
gio/gapplicationimpl-dbus.c: In function ‘g_application_impl_attempt_primary’:
gio/gapplicationimpl-dbus.c:364:3: error: ‘static’ is not at beginning of declaration [-Werror=old-style-declaration]
   const static GDBusInterfaceVTable vtable = {
   ^~~~~
gio/gapplicationimpl-dbus.c:368:3: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gapplicationimpl-dbus.c:30:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/gapplicationimpl-dbus.c: In function ‘g_application_impl_command_line’:
gio/gapplicationimpl-dbus.c:771:3: error: ‘static’ is not at beginning of declaration [-Werror=old-style-declaration]
   const static GDBusInterfaceVTable vtable = {
   ^~~~~
gio/gapplicationimpl-dbus.c:773:3: error: missing initializer for field ‘get_property’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gapplicationimpl-dbus.c:30:
gio/gdbusconnection.h:387:33: note: ‘get_property’ declared here
   GDBusInterfaceGetPropertyFunc get_property;
                                 ^~~~~~~~~~~~