Fixing various warnings in glib/tests/mainloop.c
glib/tests/mainloop.c:51:1: error: missing initializer for field ‘closure_callback’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
 };
 ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from glib/tests/mainloop.c:23:
glib/gmain.h:262:19: note: ‘closure_callback’ declared here
   GSourceFunc     closure_callback;
                   ^~~~~~~~~~~~~~~~
glib/tests/mainloop.c:411:1: error: missing initializer for field ‘closure_callback’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
 };
 ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from glib/tests/mainloop.c:23:
glib/gmain.h:262:19: note: ‘closure_callback’ declared here
   GSourceFunc     closure_callback;
                   ^~~~~~~~~~~~~~~~
glib/tests/mainloop.c: In function ‘test_ready_time’:
glib/tests/mainloop.c:931:3: error: missing initializer for field ‘finalize’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
   };
   ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from glib/tests/mainloop.c:23:
glib/gmain.h:258:14: note: ‘finalize’ declared here
   void     (*finalize) (GSource    *source); /* Can be NULL */
              ^~~~~~~~
glib/tests/mainloop.c: In function ‘test_unref_while_pending’:
glib/tests/mainloop.c:1073:3: error: missing initializer for field ‘closure_callback’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
   static GSourceFuncs funcs = { trivial_prepare, NULL, NULL, trivial_finalize };
   ^~~~~~
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from glib/tests/mainloop.c:23:
glib/gmain.h:262:19: note: ‘closure_callback’ declared here
   GSourceFunc     closure_callback;
                   ^~~~~~~~~~~~~~~~
In file included from glib/glibconfig.h:9,
                 from glib/gtypes.h:32,
                 from glib/galloca.h:32,
                 from glib/glib.h:30,
                 from glib/tests/mainloop.c:23:
glib/tests/mainloop.c: In function ‘write_bytes’:
glib/gmacros.h:351:26: error: comparison of integer expressions of different signedness: ‘gssize’ {aka ‘long int’} and ‘long unsigned int’ [-Werror=sign-compare]
 #define MIN(a, b)  (((a) < (b)) ? (a) : (b))
                          ^
glib/tests/mainloop.c:1131:11: note: in expansion of macro ‘MIN’
   limit = MIN (*to_write, sizeof zeros);
           ^~~
glib/gmacros.h:351:35: error: operand of ?: changes signedness from ‘gssize’ {aka ‘long int’} to ‘long unsigned int’ due to unsignedness of other operand [-Werror=sign-compare]
 #define MIN(a, b)  (((a) < (b)) ? (a) : (b))
                                   ^~~
glib/tests/mainloop.c:1131:11: note: in expansion of macro ‘MIN’
   limit = MIN (*to_write, sizeof zeros);
           ^~~
glib/tests/mainloop.c: In function ‘test_source_unix_fd_api’:
glib/tests/mainloop.c:1388:3: error: missing initializer for field ‘finalize’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
   };
   ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from glib/tests/mainloop.c:23:
glib/gmain.h:258:14: note: ‘finalize’ declared here
   void     (*finalize) (GSource    *source); /* Can be NULL */
              ^~~~~~~~