Fix missing initializers in gio/tests/dbus-appinfo.c
gio/tests/dbus-appinfo.c:177:3: error: missing initializer for field ‘parameter_type’ of ‘GActionEntry’ {aka ‘const struct _GActionEntry’} [-Werror=missing-field-initializers]
   { "frob",         test_application_frob              },
   ^
In file included from gio/gio.h:31,
                 from gio/tests/dbus-appinfo.c:20:
gio/gactionmap.h:63:16: note: ‘parameter_type’ declared here
   const gchar *parameter_type;
                ^~~~~~~~~~~~~~
gio/tests/dbus-appinfo.c:178:3: error: missing initializer for field ‘parameter_type’ of ‘GActionEntry’ {aka ‘const struct _GActionEntry’} [-Werror=missing-field-initializers]
   { "tweak",        test_application_tweak             },
   ^
In file included from gio/gio.h:31,
                 from gio/tests/dbus-appinfo.c:20:
gio/gactionmap.h:63:16: note: ‘parameter_type’ declared here
   const gchar *parameter_type;
                ^~~~~~~~~~~~~~
gio/tests/dbus-appinfo.c:179:3: error: missing initializer for field ‘parameter_type’ of ‘GActionEntry’ {aka ‘const struct _GActionEntry’} [-Werror=missing-field-initializers]
   { "twiddle",      test_application_twiddle           },
   ^
In file included from gio/gio.h:31,
                 from gio/tests/dbus-appinfo.c:20:
gio/gactionmap.h:63:16: note: ‘parameter_type’ declared here
   const gchar *parameter_type;
                ^~~~~~~~~~~~~~
gio/tests/dbus-appinfo.c:180:3: error: missing initializer for field ‘parameter_type’ of ‘GActionEntry’ {aka ‘const struct _GActionEntry’} [-Werror=missing-field-initializers]
   { "quit",         test_application_quit              }
   ^
In file included from gio/gio.h:31,
                 from gio/tests/dbus-appinfo.c:20:
gio/gactionmap.h:63:16: note: ‘parameter_type’ declared here
   const gchar *parameter_type;
                ^~~~~~~~~~~~~~