Fix missing initializer warning in gio/tests/gdbus-peer.c
gio/tests/gdbus-peer.c:234:1: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-peer.c:23:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-peer.c:1027:1: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-peer.c:23:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~