Fix missing initializer warning in gio/gcontenttype.c
gio/gcontenttype.c: In function ‘load_comment_for_mime_helper’:
gio/gcontenttype.c:409:3: error: missing initializer for field ‘passthrough’ of ‘GMarkupParser’ {aka ‘struct _GMarkupParser’} [-Werror=missing-field-initializers]
   };
   ^
In file included from glib/glib.h:60,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gcontenttype.h:28,
                 from gio/gcontenttypeprivate.h:24,
                 from gio/gcontenttype.c:28:
glib/gmarkup.h:172:10: note: ‘passthrough’ declared here
   void (*passthrough)    (GMarkupParseContext *context,
          ^~~~~~~~~~~