Fix missing initializer warning in gio/gtask.c
gio/gtask.c:2039:1: error: missing initializer for field ‘closure_callback’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
 };
 ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gtask.h:26,
                 from gio/gtask.c:22:
glib/gmain.h:262:19: note: ‘closure_callback’ declared here
   GSourceFunc     closure_callback;
                   ^~~~~~~~~~~~~~~~