fixup! gspawn: Optimize with posix_spawn codepath
Needed to fix build failure on android_ndk_r16_api21_arm64
../glib/gspawn.c:64:66: error: missing binary operator before token "("
     (!defined(__GLIBC__) || (defined(__GLIBC__) && __GLIBC_PREREQ(2,24)))
                                                                  ^