Fix missing initializer warnings in gio/tests/gdbus-export.c
gio/tests/gdbus-export.c:130:1: error: missing initializer for field ‘properties’ of ‘GDBusInterfaceInfo’ {aka ‘const struct _GDBusInterfaceInfo’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:54,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusintrospection.h:156:25: note: ‘properties’ declared here
   GDBusPropertyInfo   **properties;
                         ^~~~~~~~~~
gio/tests/gdbus-export.c:202:1: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-export.c:315:1: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-export.c:697:1: error: missing initializer for field ‘padding’ of ‘GDBusSubtreeVTable’ {aka ‘const struct _GDBusSubtreeVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusconnection.h:533:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-export.c:751:1: error: missing initializer for field ‘padding’ of ‘GDBusSubtreeVTable’ {aka ‘const struct _GDBusSubtreeVTable’} [-Werror=missing-field-initializers]
 };
 ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusconnection.h:533:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~
gio/tests/gdbus-export.c: In function ‘test_async_properties’:
gio/tests/gdbus-export.c:1733:3: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-export.c:21:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~