Fix missing initializer warning in gio/gsettingsschema.c
gio/gsettingsschema.c: In function ‘parse_into_text_tables’:
gio/gsettingsschema.c:674:3: error: missing initializer for field ‘gettext_domain’ of ‘TextTableParseInfo’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
   TextTableParseInfo info = { summaries, descriptions };
   ^~~~~~~~~~~~~~~~~~
gio/gsettingsschema.c:464:15: note: ‘gettext_domain’ declared here
   GSList     *gettext_domain;
               ^~~~~~~~~~~~~~