Fix missing initializer warning in gio/gmenuexporter.c
gio/gmenuexporter.c: In function ‘g_dbus_connection_export_menu_model’:
gio/gmenuexporter.c:787:3: error: missing initializer for field ‘get_property’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gmenuexporter.h:23,
                 from gio/gmenuexporter.c:22:
gio/gdbusconnection.h:387:33: note: ‘get_property’ declared here
   GDBusInterfaceGetPropertyFunc get_property;
                                 ^~~~~~~~~~~~