giowin32: Fix uninitialised variable error on msys2-clang64
I guess a compiler upgrade on msys2 has happened, because this wasn’t a
problem before, and the code hasn’t changed.

Fixes the warning:
```
../glib/giowin32.c:1828:47: error: variable 'c' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1828 |   channel->is_writeable = WriteFile (handle, &c, 0, &count, NULL);
      |                                               ^
1 error generated.
```

Signed-off-by: Philip Withnall <pwithnall@gnome.org>