Fix missing initializer warning in gio/gdelayedsettingsbackend.c
gio/gdelayedsettingsbackend.c: In function ‘delayed_backend_path_writable_changed’:
gio/gdelayedsettingsbackend.c:404:7: error: missing initializer for field ‘index’ of ‘CheckPrefixState’ {aka ‘struct <anonymous>’} [-Werror=missing-field-initializers]
       CheckPrefixState state = { path, g_new (const gchar *, n_keys) };
       ^~~~~~~~~~~~~~~~
gio/gdelayedsettingsbackend.c:373:9: note: ‘index’ declared here
   gsize index;
         ^~~~~