gioerror: Map ETXTBSY to G_FILE_ERROR_BUSY
It's a busy text file, but we don't care much about specifics so we
can just return the generic busy error.

(cherry-picked from commit 6bc6b7ef3012487966a99a5db06d27000205ab38)