Fix missing initializer warning in gio/gdbusconnection.c
gio/gdbusconnection.c: In function ‘g_dbus_connection_register_object_with_closures’:
gio/gdbusconnection.c:5511:5: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
     };
     ^
In file included from gio/gdbusconnection.c:102:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~