Fix missing initializer in tests/gobject/defaultiface.c
tests/gobject/defaultiface.c: In function ‘test_dynamic_iface_register’:
tests/gobject/defaultiface.c:126:5: error: missing initializer for field ‘class_data’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
     };
     ^
In file included from gobject/gobject.h:24,
                 from gobject/gbinding.h:29,
                 from glib/glib-object.h:23,
                 from tests/gobject/defaultiface.c:25:
gobject/gtype.h:1050:26: note: ‘class_data’ declared here
   gconstpointer          class_data;
                          ^~~~~~~~~~