Fixing missing initializer in gobject/gtypemodule.c
gobject/gtypemodule.c: In function ‘g_type_module_get_type’:
gobject/gtypemodule.c:154:7: error: missing initializer for field ‘value_table’ of ‘GTypeInfo’ {aka ‘const struct _GTypeInfo’} [-Werror=missing-field-initializers]
       };
       ^
In file included from gobject/gtypeplugin.h:24,
                 from gobject/gtypemodule.c:22:
gobject/gtype.h:1058:26: note: ‘value_table’ declared here
   const GTypeValueTable *value_table;
                          ^~~~~~~~~~~