Fix missing initializer warnings in gio/gapplication.c
gio/gapplication.c: In function ‘g_application_parse_command_line’:
gio/gapplication.c:544:11: error: missing initializer for field ‘arg_description’ of ‘GOptionEntry’ {aka ‘struct _GOptionEntry’} [-Werror=missing-field-initializers]
           N_("Enter GApplication service mode (use from D-Bus service files)") },
           ^~
In file included from glib/glib.h:64,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gapplication.h:27,
                 from gio/gapplication.c:23:
glib/goption.h:267:16: note: ‘arg_description’ declared here
   const gchar *arg_description;
                ^~~~~~~~~~~~~~~
gio/gapplication.c:556:11: error: missing initializer for field ‘arg_description’ of ‘GOptionEntry’ {aka ‘struct _GOptionEntry’} [-Werror=missing-field-initializers]
           N_("Override the application’s ID") },
           ^~
In file included from glib/glib.h:64,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gapplication.h:27,
                 from gio/gapplication.c:23:
glib/goption.h:267:16: note: ‘arg_description’ declared here
   const gchar *arg_description;
                ^~~~~~~~~~~~~~~
gio/gapplication.c:568:11: error: missing initializer for field ‘arg_description’ of ‘GOptionEntry’ {aka ‘struct _GOptionEntry’} [-Werror=missing-field-initializers]
           N_("Replace the running instance") },
           ^~
In file included from glib/glib.h:64,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gapplication.h:27,
                 from gio/gapplication.c:23:
glib/goption.h:267:16: note: ‘arg_description’ declared here
   const gchar *arg_description;
                ^~~~~~~~~~~~~~~