Fix missing initializer warning in gio/tests/gdbus-peer-object-manager.c
gio/tests/gdbus-peer-object-manager.c: In function ‘mock_interface_get_vtable’:
gio/tests/gdbus-peer-object-manager.c:111:3: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gio.h:52,
                 from gio/tests/gdbus-peer-object-manager.c:23:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~