Fix missing initializer warning in gio/gmenuexporter.c
gio/gmenuexporter.c: In function ‘g_dbus_connection_export_menu_model’:
gio/gmenuexporter.c:788:3: error: missing initializer for field ‘padding’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gmenuexporter.h:23,
                 from gio/gmenuexporter.c:22:
gio/gdbusconnection.h:395:12: note: ‘padding’ declared here
   gpointer padding[8];
            ^~~~~~~