Fix missing initializer warning in gio/gpollableutils.c
gio/gpollableutils.c:92:1: error: missing initializer for field ‘closure_marshal’ of ‘GSourceFuncs’ {aka ‘struct _GSourceFuncs’} [-Werror=missing-field-initializers]
 };
 ^
In file included from glib/giochannel.h:33,
                 from glib/glib.h:54,
                 from gobject/gbinding.h:28,
                 from glib/glib-object.h:23,
                 from gio/gioenums.h:28,
                 from gio/giotypes.h:28,
                 from gio/gio.h:26,
                 from gio/gpollableinputstream.h:26,
                 from gio/gpollableutils.c:23:
glib/gmain.h:263:23: note: ‘closure_marshal’ declared here
   GSourceDummyMarshal closure_marshal; /* Really is of type GClosureMarshal */
                       ^~~~~~~~~~~~~~~