Fixing improper signedness in glib/ghash.c
hash_table->size is a gint (seems that somebody (in gio?) is using
negative sizes to mean something which is not documented).

glib/ghash.c: In function ‘g_hash_table_resize’:
glib/ghash.c:820:24: error: comparison of integer expressions of different signedness: ‘gint’ {aka ‘int’} and ‘guint’ {aka ‘unsigned int’} [-Werror=sign-compare]
   if (hash_table->size > old_size)
                        ^
glib/ghash.c:839:24: error: comparison of integer expressions of different signedness: ‘gint’ {aka ‘int’} and ‘guint’ {aka ‘unsigned int’} [-Werror=sign-compare]
   if (hash_table->size < old_size)
                        ^
glib/ghash.c: In function ‘g_hash_table_get_keys_as_array’:
glib/ghash.c:2173:17: error: comparison of integer expressions of different signedness: ‘guint’ {aka ‘unsigned int’} and ‘gint’ {aka ‘int’} [-Werror=sign-compare]
   for (i = 0; i < hash_table->size; i++)
                 ^