In the sys/mnttab.h case, use mnt_mntopts
Solaris, apparently the sole user of the sys/mnttab.h case, doesn't
have mnt_opts. It does however have mnt_mntopts.

This fixes the build on SmartOS which is failing with the following
compiler error:

../gio/gunixmounts.c: In function '_g_get_unix_mounts':
../gio/gunixmounts.c:739:53: error: 'struct mnttab' has no member named 'mnt_opts'; did you mean 'mnt_mntopts'?
                                              mntent.mnt_opts,
                                                     ^~~~~~~~
                                                     mnt_mntopts