gerror: Add support for extended errors
This commit adds a G_DEFINE_ERROR_TYPE macro and
g_error_domain_register() functions to register extended error
domains. This feature uses tagged quarks to avoid the overhead of
locking when the domain is not an extended one (which is likely going
to be a majority of cases).