tests/gobject: Fix -Wcast-function-type-mismatch warning
Test objects-refcount1 is built with -Werror (see !3139).
This causes a compilation failure on clang-cl:

  glib/gobject/tests/objects-refcount1.c(64,7):
  error: cast from 'void (*)(GTestClass *)' (aka 'void (*)(struct _GTestClass *)')
  to 'GClassInitFunc' (aka 'void (*)(void *, void *)') converts to incompatible
  function type [-Werror,-Wcast-function-type-mismatch]
     64 |       (GClassInitFunc) my_test_class_init,
        |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~