Fix missing initializer warning in gio/glib-compile-resources.c
gio/glib-compile-resources.c: In function ‘parse_resource_file’:
gio/glib-compile-resources.c:553:3: error: missing initializer for field ‘passthrough’ of ‘GMarkupParser’ {aka ‘struct _GMarkupParser’} [-Werror=missing-field-initializers]
   GMarkupParser parser = { start_element, end_element, text };
   ^~~~~~~~~~~~~
In file included from glib/glib.h:60,
                 from gio/glib-compile-resources.c:22:
glib/gmarkup.h:172:10: note: ‘passthrough’ declared here
   void (*passthrough)    (GMarkupParseContext *context,
          ^~~~~~~~~~~