Fix missing initializer warning in gio/gactiongroupexporter.c
gio/gactiongroupexporter.c: In function ‘g_dbus_connection_export_action_group’:
gio/gactiongroupexporter.c:542:3: error: missing initializer for field ‘get_property’ of ‘GDBusInterfaceVTable’ {aka ‘const struct _GDBusInterfaceVTable’} [-Werror=missing-field-initializers]
   };
   ^
In file included from gio/gactiongroupexporter.c:28:
gio/gdbusconnection.h:387:33: note: ‘get_property’ declared here
   GDBusInterfaceGetPropertyFunc get_property;
                                 ^~~~~~~~~~~~